In [1]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

1) Create an array containing 4 string elements: your first name, your last name, your birth
state and your favorite color.

In [2]:
my_array=(['Lydia','Knutson','Japan','Blue'])
my_array

['Lydia', 'Knutson', 'Japan', 'Blue']

a. Use a numpy function to make all elements uppercase.

In [3]:
m_new_array=np.char.upper(my_array)
m_new_array

array(['LYDIA', 'KNUTSON', 'JAPAN', 'BLUE'], dtype='<U7')

b. Use a numpy function to count the number of times the letter “a” appears in each
element of your array.

In [4]:
count_a=np.char.count(my_array,"a")
count_a

array([1, 0, 2, 0])

c. Optional: Use a numpy function to find the length of each element in the array.
You may need to Google this.

In [5]:
st=np.vectorize(len)
print(st(my_array))

[5 7 5 4]


2) Create an array containing EVERY OTHER odd number starting with 1 and ending with
(and including) 41.

In [6]:
numbers_array=np.arange(1,47,4)
numbers_array

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

a. Use numpy to find the sum and the product of the elements of this array. NOTE:
This will require you to convert the elements of your array to floats using the
astype method.

In [7]:
sum_array=np.sum(numbers_array)
sum_array

276

In [8]:
product_array=np.prod(numbers_array)
product_array

616159193

b. Use numpy to take the natural log of each element.

In [9]:
log_array=np.log(numbers_array)
log_array

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

c. Optional: The numpy function np.diff finds the difference between adjacent
elements of an array. Find the SUM of adjacent elements of this array.

In [10]:
num1=np.delete(numbers_array,1)
num2=np.delete(numbers_array,-1)
num1+num2

array([ 2, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86])